### ISSUE TITLE
Linky v sidebaru

### ISSUE THREAD

**Issue by Halama** [keboola/kbc-bootstrap#5]
![image](https://cloud.githubusercontent.com/assets/903531/6188441/5f65bf3c-b391-11e4-9d97-db4a813fa34a.png)

Text se zobrazuje moc velkým písmem protože se na něj uplatňuje pravidlo:
```css
.kbc-user-links>.nav>li>a span {
  font-size: 16px;
  position: relative;
  top: 2px;
  padding-right: 5px;
}
```

V nařezaném demu je to ok protože texty nejsou ve spanu ale jsou jako textový uzel, to v Reactu bohužel nejde text vždy obalí do spanu viz. níže. 

```html
<li data-reactid=".0.1.0.0.2.1.0.0">
  <a href="" data-reactid=".0.1.0.0.2.1.0.0.0">
   <span class="kbc-icon-comment" data-reactid=".0.1.0.0.2.1.0.0.0.0"></span>
   <span data-reactid=".0.1.0.0.2.1.0.0.0.1"> Support </span>
  </a>
</li>
```
